#!/usr/bin/env ruby
require 'thor'
require 'open3'
require 'git_wrapper'

GitWrapper.logger.level = Logger::ERROR

class VersionInfo
  attr_accessor :major, :minor, :build

  def initialize(version)
    parts = version.split '.'
    @major = parts[0].to_i
    @minor = parts[1].to_i
    @build = parts[2].to_i
  end

  def increment(part)
    send("#{part}=", send("#{part}") + 1)
    self
  end

  def reset(part)
    send("#{part}=", 0)
    self
  end

  def to_s
    "#{major}.#{minor}.#{build}"
  end

  def <=>(other)
    return major <=> other.major if (major <=> other.major) != 0
    return minor <=> other.minor if (minor <=> other.minor) != 0
    build <=> other.build
  end

end

class Version < Thor

  desc 'last', 'Get last version'
  def last
    return unless valid_repo?
    puts last_version
  end

  desc 'build', 'Increment build version (0.0.1)'
  def build
    release last_version.increment(:build)
  end

  desc 'minor', 'Increment minor version (0.1.0)'
  def minor
    release last_version.increment(:minor).reset(:build)
  end

  desc 'major', 'Increment major version (1.0.0)'
  def major
    release last_version.increment(:major).reset(:minor).reset(:build)
  end

  desc 'release', 'Generate tag for specific version (Tag: v1.2.3)'
  def release(version)
    return unless valid_repo?
    return if !version || !valid_version?

    puts "Generating version #{version}"

    puts '- Pushing master'
    File.open("#{repo.location}/.version", 'w'){|f| f.write version}
    repo.add '.version'
    repo.commit "Release version #{version}"
    repo.push

    puts '- Creating tag'
    repo.tag "v#{version}"

    puts '- Pushing tag'
    repo.push 'origin', "v#{version}"
  end

  desc 'remove', 'Remove specific version from git repo (1.4.6)'
  def remove(version)
    return unless valid_repo?

    puts "Removing version #{version}"

    puts '- Removing local tag'
    repo.remove_tag "v#{version}"

    puts '- Removing remote tag'
    repo.push 'origin', ":v#{version}"
  end

  desc 'fix', 'Create new branch incrementing build'
  def fix
    return if !valid_repo? || !valid_version?

    version = "fix_#{last_version}"

    puts "Updating branch #{repo.current_branch}"
    repo.pull

    puts "Creating and checkouting branch #{version}"
    repo.checkout 'master', version
  end

  desc 'gem', 'Publish private gem version'
  def gem
    return unless valid_repo? && valid_gem? && valid_pending_changes?

    gemspec = Gem::Specification.load(gem_file)

    puts "Generating version #{gemspec.version}"

    puts '- Pushing changes'
    repo.push

    puts '- Creating tag'
    repo.tag "v#{gemspec.version}"

    puts '- Pushing tag'
    repo.push 'origin', "v#{gemspec.version}"

    puts '- Packaging gem'
    Open3.popen3 'rake build' do |i, o, e, t|
      puts o.readlines
      puts e.readlines
    end

    puts '- Sending to geminabox'
    Open3.popen3 "gem inabox pkg/#{gemspec.name}-#{gemspec.version}.gem" do |i, o, e, t|
      puts o.readlines
      puts e.readlines
    end
  end

  private

  def repo
    GitWrapper::Repository.new Dir.pwd
  end

  def valid_repo?
    puts "Invalid application path [#{repo.location}]" unless repo.initialized?
    repo.initialized?
  end

  def valid_gem?
    unless gem_file
      puts "Is not gem path [#{repo.location}]"
      return false
    end
    true
  end

  def gem_file
    Dir.glob("#{repo.location}/*.gemspec").first
  end

  def valid_pending_changes?
    if repo.status.any?
      puts "There are pending changes (#{repo.status.count})"
      false
    else
      true
    end
  end

  def valid_version?
    unless repo.current_branch == 'master'
      puts "Invalid branch #{repo.current_branch} (checkout master)" 
      return false
    end
    true
  end

  def last_version
    versions = repo.tags.
        select { |t| t.match /v[0-9]+\.[0-9]+\.[0-9]+/ }.
        map { |t| VersionInfo.new(t[1..-1]) }.
        sort
    versions.last || VersionInfo.new('v0.0.0')
  end

end

Version.start